### ISSUE TITLE
its broken

### ISSUE THREAD

**Issue by UnbanTwin** [thisandagain/simple#2]
Hey! when I try to start simple I get the following error: 

/usr/local/lib/node_modules/simple/bin/index.js:59
    path.exists(filename, function(exists) {
         ^
TypeError: undefined is not a function
    at Server.<anonymous> (/usr/local/lib/node_modules/simple/bin/index.js:59:10)
    at Server.emit (events.js:110:17)
    at HTTPParser.parserOnIncoming [as onIncoming](_http_server.js:491:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:111:23)
    at Socket.socketOnData (_http_server.js:343:22)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:538:20)

**Comment by thisandagain** [comment]
Hi @wizardsambolton ... this project is no longer maintained. I recommend you use `python -m SimpleHTTPServer` instead.
